services:
  _defaults:
    public: true
    
  prestashop.module.dottgnotices.service.authorization_bank:
    class: 'PrestaShop\Module\Dottgnotices\Service\AuthorizationBank'
    arguments: ['@prestashop.adapter.legacy.configuration']

  prestashop.module.dottgnotices.service.receiving_incoming_messages:
    class: 'PrestaShop\Module\Dottgnotices\Service\ReceivingIncomingMessages'
    arguments: ['@prestashop.adapter.legacy.configuration']   


  
   